<?php

/**
 * @file
 * Contains inchworm.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function inchworm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the inchworm module.
    case 'help.page.inchworm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
